#lang info
(define collection "knight")
(define deps '("base" "parser-tools"))
(define build-deps '("racket-doc"))
(define pkg-desc "An implementation of sampersand's Knight in Racket.")
(define version "0.1.0")
(define pkg-authors '(ThePuzzlemaker))
(define license '(Apache-2.0 OR MIT))
(define compile-omit-paths '("private"))
(define test-omit-paths '("private"))
